#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Info displays", "Info-Anzeigen"},
    {"Client Settings", "Client-Einstellungen"},
    {"Name tag behind your name in chat, notifications and other global options.", "Namens-Tag hinter deinem Namen im Chat, Benachrichtigungen und weitere globale Optionen."},
    {"Client tag", "Client-Tag"},
    {"Shown behind your own name in Better Chat and in the Tab List. Only you see it, nothing is sent to the server.", "Wird hinter deinem eigenen Namen im Better Chat und in der Tab-Liste angezeigt. Nur du siehst ihn, es wird nichts an den Server gesendet."},
    {"Client tag behind my name", "Client-Tag hinter meinem Namen"},
    {"Tag text", "Tag-Text"},
    {"Tag color", "Tag-Farbe"},
    {"Tag position", "Tag-Position"},
    {"Inside the name brackets", "In den Namens-Klammern"},
    {"Before the message", "Vor der Nachricht"},
    {"Tag in brackets", "Tag in Klammern"},
    {"Also in the Tab List", "Auch in der Tab-Liste"},
    {"Notifications", "Benachrichtigungen"},
    {"One switch for steady frame times: turns on System Boost, Low Latency and the Frame Limiter and pauses post effects and extras. Your old setup returns when you switch it off.", "Ein Schalter für gleichmäßige Frametimes: schaltet System Boost, Low Latency und den Frame Limiter ein und pausiert Post-Effekte und Extras. Dein altes Setup kommt zurück, sobald du ihn ausschaltest."},
    {"Pause post effects", "Post-Effekte pausieren"},
    {"Pause extras (pet, petals, games)", "Extras pausieren (Pet, Blütenblätter, Spiele)"},
    {"Maps to avoid (comma)", "Zu meidende Karten (Komma)"},
    {"Demo server", "Demo-Server"},
    {"Automatic", "Automatisch"},
    {"Slot 1", "Platz 1"},
    {"Slot 2", "Platz 2"},
    {"Slot 3", "Platz 3"},
    {"Slot 4", "Platz 4"},
    {"Slot 5", "Platz 5"},
    {"Slot 6", "Platz 6"},
    {"Slot 7", "Platz 7"},
    {"Slot 8", "Platz 8"},
    {"Slot 9", "Platz 9"},
    {"Key 1", "Taste 1"},
    {"Command 1", "Befehl 1"},
    {"Text 1", "Text 1"},
    {"Profile 1", "Profil 1"},
    {"Key 2", "Taste 2"},
    {"Command 2", "Befehl 2"},
    {"Text 2", "Text 2"},
    {"Profile 2", "Profil 2"},
    {"Key 3", "Taste 3"},
    {"Command 3", "Befehl 3"},
    {"Text 3", "Text 3"},
    {"Profile 3", "Profil 3"},
    {"Key 4", "Taste 4"},
    {"Command 4", "Befehl 4"},
    {"Text 4", "Text 4"},
    {"Profile 4", "Profil 4"},
    {"Key 5", "Taste 5"},
    {"Command 5", "Befehl 5"},
    {"Text 5", "Text 5"},
    {"Profile 5", "Profil 5"},
    {"Key 6", "Taste 6"},
    {"Command 6", "Befehl 6"},
    {"Text 6", "Text 6"},
    {"Profile 6", "Profil 6"},
    {"Key 7", "Taste 7"},
    {"Command 7", "Befehl 7"},
    {"Text 7", "Text 7"},
    {"Profile 7", "Profil 7"},
    {"Key 8", "Taste 8"},
    {"Command 8", "Befehl 8"},
    {"Text 8", "Text 8"},
    {"Profile 8", "Profil 8"},
    {"Key 9", "Taste 9"},
    {"Command 9", "Befehl 9"},
    {"Text 9", "Text 9"},
    {"Profile 9", "Profil 9"},
    {"Key 10", "Taste 10"},
    {"Command 10", "Befehl 10"},
    {"Text 10", "Text 10"},
    {"Profile 10", "Profil 10"},
    {"Key 11", "Taste 11"},
    {"Command 11", "Befehl 11"},
    {"Text 11", "Text 11"},
    {"Profile 11", "Profil 11"},
    {"Key 12", "Taste 12"},
    {"Command 12", "Befehl 12"},
    {"Text 12", "Text 12"},
    {"Profile 12", "Profil 12"},
    {"Better Chat needs game data for this version. Until then the tag only shows in the Tab List.", "Better Chat braucht Spieldaten für diese Version. Bis dahin erscheint das Tag nur in der Tab-Liste."},
    {"Turn on Better Chat", "Better Chat einschalten"},
    {"Search all modules …", "Alle Module durchsuchen …"},
    {"Type to search modules …", "Tippen, um Module zu suchen …"},
    {"{} modules · {} ready", "{} Module · {} bereit"},
    {"{} starred", "{} markiert"},
    {"Star modules to pin them here", "Markiere Module mit dem Stern, dann stehen sie hier"},
    {"Wings, capes, bandanas · free", "Flügel, Capes, Bandanas · gratis"},
    {"Language, chat tag, look", "Sprache, Chat-Tag, Aussehen"},
    {"QUICK SWITCHES", "SCHNELLSCHALTER"},
    {"Right Shift again opens the full menu · Esc closes", "Rechts-Shift noch einmal öffnet das ganze Menü · Esc schließt"},
    {"Favorites", "Favoriten"},
    {"Pick a module to see its settings", "Wähle ein Modul, um seine Einstellungen zu sehen"},
    {"Profile", "Profil"},
    {"Menu", "Menü"},
    {"Watermark", "Watermark"},
    {"Switch many modules at once. Modules that are blocked on your server or need game data stay as they are.", "Schaltet viele Module auf einmal. Module, die auf deinem Server gesperrt sind oder Spieldaten brauchen, bleiben wie sie sind."},
    {"Minimal", "Minimal"},
    {"PvP essentials", "PvP-Grundausstattung"},
    {"Everything off", "Alles aus"},
    {"Reset all HUD positions", "Alle HUD-Positionen zurücksetzen"},
    {"List", "Liste"},
    {"Show more modules", "Mehr Module anzeigen"},
    {"Adds fun extras and rarely used modules to the list.", "Fügt Spaß-Extras und selten genutzte Module zur Liste hinzu."},
    {"Your character. The 3D preview of equipped cosmetics comes with the first set.", "Deine Figur. Die 3D-Vorschau ausgerüsteter Cosmetics kommt mit dem ersten Set."},
    {"Chat & watermark", "Chat & Watermark"},
    {"About", "Über"},
    {"Wings", "Flügel"},
    {"Capes", "Capes"},
    {"Head", "Kopf"},
    {"Body", "Körper"},
    {"Feet", "Füße"},
    {"Cosmetics", "Cosmetics"},
    {"Equip", "Ausrüsten"},
    {"Equipped", "Ausgerüstet"},
    {"No cosmetics installed yet. Wings, capes and bandanas arrive with the first release and will show up here.", "Noch keine Cosmetics installiert. Flügel, Capes und Bandanas kommen mit dem ersten Release und erscheinen dann hier."},
    {"Nothing in this category.", "In dieser Kategorie ist nichts."},
    {"No favorites yet. Click the star next to a module.", "Noch keine Favoriten. Klicke auf den Stern neben einem Modul."},
    {"Watermark in the inventory", "Watermark im Inventar"},
    {"Default HUD size", "Standard-Größe der HUD-Module"},
    {"Menu background blur", "Hintergrund-Unschärfe im Menü"},
    {"Blur", "Unschärfe"},
    {"Blurs the game image, always or only while a menu, the inventory or the chat is open.", "Macht das Spielbild unscharf, immer oder nur bei offenem Menü, Inventar oder Chat."},
    {"Only in menus", "Nur in Menüs"},
    {"{} · {} ready", "{} · {} bereit"},
    {"Pin modules", "Module anpinnen"},
    {"Free", "Gratis"},
    {"Language, tag, look", "Sprache, Tag, Aussehen"},
    {"Right Shift again: full menu  ·  Esc: close", "Rechts-Shift noch einmal: ganzes Menü  ·  Esc: schließen"},
    {"Shader Packs", "Shader Packs"},
    {"Loads shaders on top of the game image, also on servers. Four looks are built in, your own .hlsl files go into the shaders folder. Only changes what you see.", "Lädt Shader über das Spielbild, auch auf Servern. Vier Looks sind eingebaut, eigene .hlsl-Dateien kommen in den Ordner shaders. Ändert nur, was du siehst."},
    {"Reload shaders", "Shader neu laden"},
    {"Open folder", "Ordner öffnen"},
    {"Shader", "Shader"},
    {"Game scheduling for render and input threads", "Spiel-Priorität für Render- und Eingabe-Thread"},
    {"Windows settings while Minecraft runs: precise timer, higher priority, no power saving, game scheduling for render and input threads. Reverted when you quit.", "Windows-Einstellungen, solange Minecraft läuft: präziser Timer, höhere Priorität, kein Energiesparen, Spiel-Priorität für Render- und Eingabe-Thread. Wird beim Beenden zurückgesetzt."},
    {"Mouse Sync", "Maus-Sync"},
    {"Detects your mouse, measures its polling rate and keeps your aim the same when you switch mice or change DPI.", "Erkennt deine Maus, misst die Abfragerate und hält dein Zielgefühl gleich, wenn du die Maus oder die DPI wechselst."},
    {"Keep my aim when the DPI changes", "Zielgefühl bei DPI-Wechsel beibehalten"},
    {"DPI (0 = use the measured one)", "DPI (0 = gemessenen Wert nehmen)"},
    {"Measuring distance (cm)", "Messstrecke (cm)"},
    {"No mouse found yet. Move your mouse.", "Noch keine Maus gefunden. Bewege die Maus."},
    {"{} Hz", "{} Hz"},
    {"measuring …", "wird gemessen …"},
    {"{} DPI", "{} DPI"},
    {"DPI unknown", "DPI unbekannt"},
    {"Mouse software running: %s. Your DPI is set there.", "Maus-Software läuft: %s. Dort stellst du deine DPI ein."},
    {"Measure DPI", "DPI messen"},
    {"Put the mouse at the left end of a ruler, then move it exactly %.0f cm to the right in a straight line and press Done.", "Setze die Maus links an ein Lineal, bewege sie genau %.0f cm gerade nach rechts und drücke Fertig."},
    {"Done", "Fertig"},
    {"Use as my reference", "Als meine Referenz nehmen"},
    {"Reference: %d DPI (the DPI your in-game sensitivity was set for).", "Referenz: %d DPI (die DPI, für die deine Spiel-Empfindlichkeit eingestellt ist)."},
    {"%d Hz is low. Raise the polling rate to 1000 Hz or more in your mouse software.", "%d Hz ist niedrig. Stelle die Abfragerate in deiner Maus-Software auf 1000 Hz oder mehr."},
    {"Very high polling rates can cost FPS in Minecraft. If it stutters, try 1000 to 2000 Hz.", "Sehr hohe Abfrageraten können in Minecraft FPS kosten. Wenn es ruckelt, probiere 1000 bis 2000 Hz."},
    {"Keeping your aim needs game data for this version. Detection and measuring work already.", "Das Zielgefühl beibehalten braucht Spieldaten für diese Version. Erkennung und Messung funktionieren schon."},
    {"Music", "Musik"},
    {"Shows what Spotify, Apple Music, Deezer or Amazon Music plays and lets you control it with keys, without leaving the game.", "Zeigt, was Spotify, Apple Music, Deezer oder Amazon Music spielt, und steuert es per Taste, ohne das Spiel zu verlassen."},
    {"No music app found. Start Spotify, Apple Music, Deezer or Amazon Music.", "Keine Musik-App gefunden. Starte Spotify, Apple Music, Deezer oder Amazon Music."},
    {"Found: %s", "Gefunden: %s"},
    {"Keys control whichever player Windows treats as active. The volume keys change the volume of the music app only, not of Minecraft.", "Die Tasten steuern den Player, den Windows als aktiv ansieht. Die Lautstärke-Tasten ändern nur die Lautstärke der Musik-App, nicht die von Minecraft."},
    {"No music", "Keine Musik"},
    {"Play / pause", "Wiedergabe / Pause"},
    {"Next song", "Nächster Song"},
    {"Previous song", "Vorheriger Song"},
    {"Music volume up", "Musik lauter"},
    {"Music volume down", "Musik leiser"},
    {"Mute music", "Musik stumm"},
    {"Slowest: {} ({:.2f} ms)", "Langsamstes: {} ({:.2f} ms)"},
    {"Slim arms (Alex model)", "Schmale Arme (Alex-Modell)"},
    {"Turn speed", "Drehgeschwindigkeit"},
    {"Animation speed", "Animationsgeschwindigkeit"},
    {"Equip a cosmetic to change its colors here.", "Rüste ein Cosmetic aus, um hier seine Farben zu ändern."},
};

i18n::Table table(entries);

}
