#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"  (demo, not sent)", "  (Demo, nicht gesendet)"},
    {"  (paused)", "  (Pause)"},
    {"  ·  ", "  ·  vor "},
    {"  ·  Best {}", "  ·  Rekord {}"},
    {"  ·  channel {}", "  ·  Kanal {}"},
    {"  ·  requested", "  ·  angefordert"},
    {"  ·  {:.0f} damage", "  ·  {:.0f} Schaden"},
    {"  ·  {:.0f}% crit", "  ·  {:.0f}% Crit"},
    {"  ·  {} hits", "  ·  {} Treffer"},
    {" blocks", " Blöcke"},
    {" for ", " für "},
    {"%.1f h", "%.1f Uhr"},
    {"%d game modules ready, %d waiting for signatures", "%d Spiel-Module bereit, %d warten auf Signaturen"},
    {"1% low and peak", "1% Low und Spitze"},
    {"1% low {:.0f} FPS  ·  peak {:.1f} ms", "1% Low {:.0f} FPS  ·  Spitze {:.1f} ms"},
    {"1.8-style swing and block animations, smaller item, own swing speed.", "Schwung- und Block-Animationen im 1.8-Stil, kleineres Item, eigene Schwunggeschwindigkeit."},
    {"2.4 GHz", "2,4 GHz"},
    {"<Max> who has the pearl?", "<Max> wer hat die Perle?"},
    {"A LAN cable is the surest fix for jitter", "LAN-Kabel ist die sicherste Lösung gegen Jitter"},
    {"A little Mochi pet in the HUD: bounces, cheers on hits, sleeps when idle.", "Kleines Mochi-Haustier im HUD: wippt, freut sich über Treffer, schläft bei Ruhe."},
    {"A rain of hearts and text on screen when you get a kill. Local only.", "Herzchen-Regen und Text auf dem Bildschirm, wenn du einen Kill machst. Nur lokal."},
    {"A red, pulsing screen edge when your health is low.", "Roter, pulsierender Rand am Bildschirm, wenn dein Leben niedrig ist."},
    {"A short look behind or to the side on a key, without changing your aim.", "Kurzer Blick nach hinten oder zur Seite per Taste, ohne die Blickrichtung zu ändern."},
    {"A short marker at the crosshair when you hit. Display only, changes nothing in the game.", "Kurzer Marker am Fadenkreuz, wenn du triffst. Nur eine Anzeige, ändert nichts am Spiel."},
    {"A small figure in the HUD that wears your armor, sneaks, sprints and flashes red when you are hit.", "Kleine Figur im HUD, die deine Rüstung trägt, schleicht, sprintet und bei Treffern rot aufblitzt."},
    {"A warmer blue-light filter for relaxed eyes, optionally automatic in the evening.", "Wärmerer Blaufilter für entspanntere Augen, auf Wunsch automatisch am Abend."},
    {"About {:.0f} ms in total until the hit", "Gesamt ca. {:.0f} ms bis zum Treffer"},
    {"Accept duel requests", "Duell-Anfragen annehmen"},
    {"Accept friend requests", "Freundschaftsanfragen annehmen"},
    {"Accept party invites", "Party-Einladungen annehmen"},
    {"Accepting", "Wird angenommen"},
    {"Active limit: %.0f FPS  ·  Monitor: %d Hz", "Aktives Limit: %.0f FPS  ·  Monitor: %d Hz"},
    {"Active: %s", "Aktiv: %s"},
    {"Adapter power saving is on", "Energiesparen des Adapters aktiv"},
    {"Add", "Addieren"},
    {"Add here", "Hier hinzufügen"},
    {"Adjust sensitivity while zooming", "Empfindlichkeit beim Zoomen anpassen"},
    {"Advanced settings", "Erweiterte Einstellungen"},
    {"After a kill", "Nach einem Kill"},
    {"All axes", "Alle Achsen"},
    {"Also report when they leave", "Auch beim Verlassen melden"},
    {"Also show a bar", "Zusätzlich Balken"},
    {"Also show players", "Spieler zusätzlich"},
    {"Also show when off", "Auch anzeigen, wenn aus"},
    {"Also when your team is eliminated", "Auch wenn dein Team ausgeschieden ist"},
    {"Always", "Immer"},
    {"Always as stars", "Immer als Sterne"},
    {"Amount", "Menge"},
    {"Announce your vote in chat", "Deine Stimme im Chat ansagen"},
    {"Announcement ({map})", "Ansage ({map})"},
    {"Append jitter", "Jitter anhängen"},
    {"Append loss", "Verlust anhängen"},
    {"Apply recommendation", "Empfehlung anwenden"},
    {"Arrow at the screen edge", "Pfeil am Bildschirmrand"},
    {"Arrows", "Pfeile"},
    {"As percent", "Als Prozent"},
    {"As sent by the server", "Wie vom Server"},
    {"Assigns your own keys to the hotbar slots, for example mouse buttons or keys next to WASD.", "Belegt die Hotbar-Plätze mit eigenen Tasten, zum Beispiel Maustasten oder Tasten neben WASD."},
    {"At the end of a game", "Am Spielende"},
    {"Auto requeue after a game", "Nach dem Spiel automatisch neu einreihen"},
    {"Automatic by server", "Automatisch nach Server"},
    {"Automatic while walking forward", "Automatisch beim Vorwärtsgehen"},
    {"Automatically switches your settings profile when you join a server and back afterwards.", "Wechselt beim Betreten eines Servers automatisch dein Einstellungs-Profil und danach wieder zurück."},
    {"Automatically writes gg at the end of a game. On a kill it is banned on some servers.", "Schreibt am Spielende automatisch gg. Beim Kill ist es auf manchen Servern verboten."},
    {"Available on this version:", "Auf dieser Version verfügbar:"},
    {"Available profiles: %s", "Vorhandene Profile: %s"},
    {"Average", "Durchschnitt"},
    {"Avoiding map {}", "Map {} wird gemieden"},
    {"Back to work", "Zurück an die Arbeit"},
    {"Background limit", "Hintergrund-Limit"},
    {"Background {:.0f}%", "Hintergrund {:.0f}%"},
    {"Balanced", "Ausgewogen"},
    {"Bar", "Leiste"},
    {"Bar color", "Balkenfarbe"},
    {"Bar width", "Breite der Leiste"},
    {"Base field of view", "Basis-Sichtfeld"},
    {"Base value", "Grundwert"},
    {"Beam height", "Strahlhöhe"},
    {"Beep", "Signalton"},
    {"Behavior", "Verhalten"},
    {"Behind", "Hinten"},
    {"Best value", "Bestwert"},
    {"Biggest share: {} ({:.0f} %)", "Größter Anteil: {} ({:.0f} %)"},
    {"Biome", "Biom"},
    {"Biome: {}", "Biom: {}"},
    {"Black", "Schwarz"},
    {"Black and white", "Schwarzweiß"},
    {"Blend mode", "Mischmodus"},
    {"Blindness", "Blindheit"},
    {"Block Game  ·  {}  ·  Level {}  ·  Lines {}  ·  Best {}", "Block Game  ·  {}  ·  Level {}  ·  Linien {}  ·  Rekord {}"},
    {"Block coordinates", "Blockkoordinaten"},
    {"Block coordinates only", "Nur Blockkoordinaten"},
    {"Block entities off (chests, signs)", "Block-Entities aus (Truhen, Schilder)"},
    {"Block pose while blocking", "Block-Pose beim Blocken"},
    {"Block shadow", "Schatten des Blocks"},
    {"Block size", "Blockgröße"},
    {"Blocks per second", "Blöcke pro Sekunde"},
    {"Blue weakness (tritanopia)", "Blauschwäche (Tritanopie)"},
    {"Bobbing strength", "Wackel-Stärke"},
    {"Both", "Beides"},
    {"Both cancel out", "Beide neutralisieren"},
    {"Bottom up", "Von unten nach oben"},
    {"Bow only", "Nur Bogen"},
    {"Break", "Pause"},
    {"Break progress", "Abbaufortschritt"},
    {"Brightness", "Helligkeit"},
    {"Brightness, contrast, gamma and vignette for the game image.", "Helligkeit, Kontrast, Gamma und Vignette für das Spielbild."},
    {"Button", "Knopf"},
    {"By name", "Nach Name"},
    {"Camera", "Kamera"},
    {"Camera bobbing", "Kamera-Wackeln"},
    {"Camera bobbing off", "Kamera-Wackeln aus"},
    {"Camera rotation", "Kamera-Rotation"},
    {"Capture", "Aufnahme"},
    {"Capture key", "Aufnahme-Taste"},
    {"Capture now", "Jetzt aufnehmen"},
    {"Center dot", "Mittelpunkt"},
    {"Change level with the mouse wheel", "Stufe per Mausrad ändern"},
    {"Change the weather only for you: turn rain and thunder off or force them.", "Wetter nur bei dir ändern: Regen und Gewitter abschalten oder erzwingen."},
    {"Changes saturation and hue of the game image, with presets and an optional rainbow cycle.", "Ändert Sättigung und Farbton des Spielbilds, mit Vorlagen und optionalem Regenbogen-Wechsel."},
    {"Changes the color of the enchantment glint on items and armor.", "Ändert die Farbe des Verzauberungs-Glanzes auf Items und Rüstung."},
    {"Changes the red tint when you or an opponent take damage.", "Ändert die rote Farbe, wenn du oder ein Gegner Schaden nehmen."},
    {"Chat key in game", "Chat-Taste im Spiel"},
    {"Check armor", "Rüstung prüfen"},
    {"Check cable and router, enable router QoS for games", "Kabel und Router prüfen, Router-QoS für Spiele aktivieren"},
    {"Check item in hand", "Item in der Hand prüfen"},
    {"Clear", "Klar"},
    {"Click", "Klack"},
    {"Click color / second color", "Klickfarbe / Zweitfarbe"},
    {"Click once and I will measure", "Klick mal, dann messe ich"},
    {"Click to frame: %.1f ms on average (%d clicks)", "Klick bis Bild: %.1f ms im Schnitt (%d Klicks)"},
    {"Click to measure the latency.", "Klicke, um die Latenz zu messen."},
    {"Client logo with heart and version as text, pill or gradient.", "Client-Logo mit Herz und Version als Text, Pille oder Verlauf."},
    {"Clock", "Uhr"},
    {"Clouds", "Wolken"},
    {"Clouds off", "Wolken aus"},
    {"Color X", "Farbe X"},
    {"Color Y", "Farbe Y"},
    {"Color Z", "Farbe Z"},
    {"Color almost broken", "Farbe fast kaputt"},
    {"Color at full draw", "Farbe bei voller Spannung"},
    {"Color bad", "Farbe schlecht"},
    {"Color by effect", "Farbe nach Effekt"},
    {"Color by health", "Farbe nach Leben"},
    {"Color by value", "Farbe nach Wert"},
    {"Color current chunk", "Farbe aktueller Chunk"},
    {"Color filter for color blindness: corrects or simulates red, green and blue weakness.", "Farbfilter für Farbsehschwäche: korrigiert oder simuliert Rot-, Grün- und Blauschwäche."},
    {"Color frame", "Farbe Bild"},
    {"Color full", "Farbe voll"},
    {"Color full health", "Farbe volles Leben"},
    {"Color good", "Farbe gut"},
    {"Color half", "Farbe halb"},
    {"Color half health", "Farbe halbes Leben"},
    {"Color high", "Farbe hoch"},
    {"Color input", "Farbe Eingabe"},
    {"Color levels", "Farbe Ebenen"},
    {"Color low", "Farbe niedrig"},
    {"Color low health", "Farbe wenig Leben"},
    {"Color medium", "Farbe mittel"},
    {"Color neighbor chunks", "Farbe Nachbarchunks"},
    {"Color network", "Farbe Netzwerk"},
    {"Color on crit", "Farbe bei Crit"},
    {"Color server", "Farbe Server"},
    {"Color swatch", "Farbfeld"},
    {"Color temperature (K)", "Farbtemperatur (K)"},
    {"Color when aiming", "Farbe beim Anvisieren"},
    {"Color when aiming at an opponent", "Farbe beim Anvisieren eines Gegners"},
    {"Color when almost done", "Farbe kurz vor fertig"},
    {"Color when low", "Farbe bei wenig Zeit"},
    {"Color while clicking", "Farbe beim Klicken"},
    {"Columns (0 = by rows)", "Spalten (0 = nach Zeilen)"},
    {"Combat displays", "Kampf-Anzeigen"},
    {"Combo record", "Combo-Rekord"},
    {"Command ", "Befehl "},
    {"Compass direction", "Himmelsrichtung"},
    {"Compass with direction, degrees and view angle, as text or as a bar.", "Kompass mit Himmelsrichtung, Grad und Blickwinkel, als Text oder als Leiste."},
    {"Connected to The Hive", "Mit The Hive verbunden"},
    {"Connected to Zeqa", "Mit Zeqa verbunden"},
    {"Connection (Wi-Fi / LAN)", "Verbindung (WLAN / LAN)"},
    {"Connection poor", "Verbindung schlecht"},
    {"Connection type unknown", "Verbindungsart unbekannt"},
    {"Connection: ", "Verbindung: "},
    {"Constant spin", "Dauerdrehung"},
    {"Content", "Inhalt"},
    {"Contrast", "Kontrast"},
    {"Copied", "Kopiert"},
    {"Copy code", "Code kopieren"},
    {"Copy custom server codes", "Custom-Server-Codes kopieren"},
    {"Copy last point", "Letzten Punkt kopieren"},
    {"Copy position to the clipboard", "Position in die Zwischenablage kopieren"},
    {"Copy to the clipboard", "In die Zwischenablage kopieren"},
    {"Count", "Anzahl"},
    {"Count hotbar only", "Nur Hotbar zählen"},
    {"Count to negatives", "Ins Minus zählen"},
    {"Counts any item that you choose.", "Zählt ein beliebiges Item, das du selbst festlegst."},
    {"Counts entities and players around you.", "Zählt Entities und Spieler in deiner Umgebung."},
    {"Counts the splash potions in your inventory.", "Zählt die Wurftränke in deinem Inventar."},
    {"Counts your arrows. Can show only while you hold a bow or crossbow.", "Zählt deine Pfeile. Kann nur zeigen, solange du Bogen oder Armbrust hältst."},
    {"Counts your hits in a row until the opponent hits you.", "Zählt deine Treffer in Folge, bis dich der Gegner trifft."},
    {"Counts your totems of undying. Can show only while you hold one.", "Zählt deine Totems der Unsterblichkeit. Kann nur zeigen, solange du eines hältst."},
    {"Crit rate", "Crit-Quote"},
    {"Critical!", "Kritisch!"},
    {"Crystal without base", "Crystal ohne Sockel"},
    {"Crystal without spin and bobbing", "Crystal ohne Drehen und Wippen"},
    {"Current", "Aktuell"},
    {"Current chunk only", "Nur aktueller Chunk"},
    {"Custom", "Eigener"},
    {"Custom command", "Eigener Befehl"},
    {"Custom grid", "Eigenes Raster"},
    {"Custom target (empty = server)", "Eigenes Ziel (leer = Server)"},
    {"Custom text", "Eigener Text"},
    {"Cycle the hue", "Farbton durchlaufen"},
    {"D {}  ", "T {}  "},
    {"Damage numbers rise from the crosshair when you hit.", "Schadenszahlen steigen vom Fadenkreuz auf, wenn du triffst."},
    {"Dark edge while zooming", "Dunkler Rand beim Zoomen"},
    {"Darkness", "Dunkelheit"},
    {"Data", "Daten"},
    {"Day", "Tag"},
    {"Day or night", "Tag oder Nacht"},
    {"Death", "Tod"},
    {"Death Run: requeue after too many deaths", "Death Run: nach zu vielen Toden neu einreihen"},
    {"Death Run: requeue as Death", "Death Run: als Death neu einreihen"},
    {"Death Run: requeue as Runner", "Death Run: als Runner neu einreihen"},
    {"Death point is on the clipboard.", "Todespunkt in der Zwischenablage."},
    {"Deaths", "Tode"},
    {"Deaths before requeue", "Tode bis zum Requeue"},
    {"Decimals", "Nachkommastellen"},
    {"Deep-fries the game image: oversaturated, grainy and harshly stepped. Pure fun.", "Frittiert das Spielbild: übersättigt, körnig und hart abgestuft. Reiner Spaß."},
    {"Default color", "Standardfarbe"},
    {"Delay (s)", "Verzögerung (s)"},
    {"Demo data (simulated game values)", "Demo-Daten (simulierte Spielwerte)"},
    {"Demo data on", "Demo-Daten aktiv"},
    {"Demo data on: all game modules show simulated values.", "Demo-Daten aktiv: alle Spiel-Module zeigen simulierte Werte."},
    {"Depth", "Tiefe"},
    {"Detect game end", "Spielende erkennen"},
    {"Detects your hardware, recommends a performance profile and applies it.", "Erkennt deine Hardware, empfiehlt ein Performance-Profil und wendet es an."},
    {"Diagnostics", "Diagnose"},
    {"Diamond", "Raute"},
    {"Direction", "Richtung"},
    {"Direction (camera)", "Richtung (Kamera)"},
    {"Display style", "Darstellung"},
    {"Display time (s, 0 = permanent)", "Anzeigedauer (s, 0 = dauerhaft)"},
    {"Display time after looking away (s)", "Anzeigedauer nach Blickwechsel (s)"},
    {"Displays are back on.", "Anzeigen sind wieder an."},
    {"Distance", "Distanz"},
    {"Distance to the block", "Abstand zum Block"},
    {"Do not change", "Nichts ändern"},
    {"Dots", "Punkte"},
    {"Down", "Runter"},
    {"Duel accept command", "Befehl zum Annehmen von Duellen"},
    {"Duel mode", "Duell-Modus"},
    {"Duel request words (comma)", "Wörter für Duell-Anfragen (Komma)"},
    {"Duos", "Duo"},
    {"Durability", "Haltbarkeit"},
    {"Duration (s)", "Dauer (s)"},
    {"Duration {}", "Dauer {}"},
    {"Dynamic (walking, jumping, sneaking)", "Dynamisch (Laufen, Springen, Schleichen)"},
    {"E", "O"},
    {"East", "Osten"},
    {"Edge width", "Breite des Rands"},
    {"Effect channels", "Effekt-Kanäle"},
    {"Effect channels:", "Effekt-Kanäle:"},
    {"Effect name", "Effektname"},
    {"Eliminated", "Ausgeschieden"},
    {"Elimination words (comma)", "Wörter fürs Ausscheiden (Komma)"},
    {"Empty hand", "Leere Hand"},
    {"Entities: {}  Players: {}", "Entities: {}  Spieler: {}"},
    {"Every click", "Jeder Klick"},
    {"Everyone together", "Alle zusammen"},
    {"Exclude team", "Team ausschließen"},
    {"Extra while flying", "Zusatz beim Fliegen"},
    {"Extra while sprinting", "Zusatz beim Sprinten"},
    {"FOV effects", "Sichtfeld-Effekte"},
    {"FPS behind it", "FPS dahinter"},
    {"Facing", "Blick"},
    {"Facing: yaw {:.1f} pitch {:.1f}", "Blick: yaw {:.1f} pitch {:.1f}"},
    {"Factor while sprinting", "Faktor beim Sprinten"},
    {"Fade out when close", "In der Nähe ausblenden"},
    {"Fall speed", "Fallgeschwindigkeit"},
    {"Falling blocks while you queue. Space drops, ESC quits.", "Fallende Blöcke für die Warteschlange. Leertaste lässt fallen, ESC beendet."},
    {"Falls asleep after (s)", "Einschlafen nach (s)"},
    {"Faster moving of items in the inventory. Banned on many servers.", "Schnelleres Bewegen von Items im Inventar. Auf vielen Servern verboten."},
    {"Favorite maps (comma)", "Lieblings-Maps (Komma)"},
    {"Field of view", "Sichtfeld"},
    {"File name", "Dateiname"},
    {"Fill color", "Füllfarbe"},
    {"Fill the faces", "Flächen füllen"},
    {"Fire Resistance", "Feuerresistenz"},
    {"Fire overlay", "Feuer-Overlay"},
    {"First person", "Erste Person"},
    {"Fixed time", "Feste Uhrzeit"},
    {"Fixed value", "Fester Wert"},
    {"Flash color", "Blinkfarbe"},
    {"Flash on a new hit", "Aufleuchten bei neuem Treffer"},
    {"Flash on warning", "Blinken bei Warnung"},
    {"Flash the screen", "Bildschirm aufblitzen"},
    {"Flash when low", "Blinken bei wenig Zeit"},
    {"Flip the Z axis (Mumble is left-handed)", "Z-Achse umkehren (Mumble ist linkshändig)"},
    {"Fog", "Nebel"},
    {"Fog color", "Nebelfarbe"},
    {"Fog off", "Nebel aus"},
    {"Folder (empty = Pictures\\Mochi)", "Ordner (leer = Bilder\\Mochi)"},
    {"Folder: %s", "Ordner: %s"},
    {"Forward / Back", "Vor / Zurück"},
    {"Forward key", "Vorwärts-Taste"},
    {"Frame", "Bild"},
    {"Frame blending", "Bildmischung"},
    {"Frame timing", "Frame-Timing"},
    {"Freelook key", "Freelook-Taste"},
    {"Freely set position, size and rotation of hand and item in first person.", "Position, Größe und Drehung von Hand und Item in der Ego-Perspektive frei einstellen."},
    {"Friend accept command", "Befehl zum Annehmen von Freunden"},
    {"Friend request words (comma)", "Wörter für Freundschaftsanfragen (Komma)"},
    {"From (hearts)", "Ab (Herzen)"},
    {"From (hour)", "Ab (Uhr)"},
    {"Full", "Voll"},
    {"Full round trip", "Volle Rundlaufzeit"},
    {"GUI scale", "GUI-Skalierung"},
    {"Game", "Spiel"},
    {"Game end words (comma)", "Wörter für Spielende (Komma)"},
    {"Game over", "Spielende"},
    {"Game time", "Spielzeit"},
    {"Game: {}  ·  Mode: {}  ·  Map: {}", "Spiel: {}  ·  Modus: {}  ·  Map: {}"},
    {"Games", "Spiele"},
    {"Glint color", "Glanzfarbe"},
    {"Gradient", "Verlauf"},
    {"Graphics", "Grafik"},
    {"Graphics card: %s", "Grafikkarte: %s"},
    {"Gravity", "Schwerkraft"},
    {"Green weakness (deuteranopia)", "Grünschwäche (Deuteranopie)"},
    {"Grid", "Raster"},
    {"Group", "Gruppe"},
    {"Grows while fading", "Wächst beim Ausblenden"},
    {"HUD parts", "HUD-Teile"},
    {"Hair color", "Haarfarbe"},
    {"Half", "Halb"},
    {"Half round trip (one way)", "Halbe Rundlaufzeit (nur Hinweg)"},
    {"Hand bobbing", "Hand-Wackeln"},
    {"Hand bobbing off", "Hand-Wackeln aus"},
    {"Hand transform", "Hand-Transformation"},
    {"Haste", "Eile"},
    {"Health", "Leben"},
    {"Health Boost", "Lebensschub"},
    {"Health bar", "Lebensbalken"},
    {"Health value", "Lebenswert"},
    {"Health {:.1f}  Hunger {:.0f}  Level {}", "Leben {:.1f}  Hunger {:.0f}  Level {}"},
    {"Heartbeat pulse", "Herzschlag-Puls"},
    {"Hearts", "Herzen"},
    {"Hearts on hits", "Herzchen bei Treffern"},
    {"Height", "Höhe"},
    {"Height (fraction)", "Höhe (Anteil)"},
    {"Height above and below you", "Höhe über und unter dir"},
    {"Hide (streamer)", "Verstecken (Streamer)"},
    {"Hide No Teaming messages", "No-Teaming-Meldungen ausblenden"},
    {"Hide after (s, 0 = never)", "Ausblenden nach (s, 0 = nie)"},
    {"Hide and Seek: requeue as Hider", "Hide and Seek: als Hider neu einreihen"},
    {"Hide and Seek: requeue as Seeker", "Hide and Seek: als Seeker neu einreihen"},
    {"Hide chat from Hive+ players", "Chat von Hive+-Spielern ausblenden"},
    {"Hide chat from players without a rank", "Chat von Spielern ohne Rang ausblenden"},
    {"Hide crystal instantly", "Crystal sofort ausblenden"},
    {"Hide empty slots", "Leere Plätze ausblenden"},
    {"Hide hand", "Hand ausblenden"},
    {"Hide in inventory, chat and pause", "In Inventar, Chat und Pause ausblenden"},
    {"Hide in third person", "In dritter Person ausblenden"},
    {"Hide join messages", "Beitritts-Meldungen ausblenden"},
    {"Hide kill streak messages", "Kill-Serien-Meldungen ausblenden"},
    {"Hide leave messages", "Verlassen-Meldungen ausblenden"},
    {"Hide main hand", "Haupthand ausblenden"},
    {"Hide offhand", "Nebenhand ausblenden"},
    {"Hide promo messages", "Werbenachrichten ausblenden"},
    {"Hide the original HUD", "Original-HUD ausblenden"},
    {"Hide the original chat", "Original-Chat ausblenden "},
    {"Hide the original crosshair", "Original-Fadenkreuz ausblenden "},
    {"Hide the original outline", "Original-Umriss ausblenden"},
    {"Hide the original scoreboard", "Original-Scoreboard ausblenden"},
    {"Hide unlock hints", "Freischalt-Hinweise ausblenden"},
    {"Hide with a key", "Verstecken per Taste"},
    {"Hides IP, coordinates, server and chat on a key. A second press brings everything back.", "Versteckt per Taste IP, Koordinaten, Server und Chat. Zweiter Druck bringt alles zurück."},
    {"Hides hand and item in first person, for a clear view or screenshots.", "Blendet Hand und Item in der Ego-Perspektive aus, für freie Sicht oder Screenshots."},
    {"High", "Hoch"},
    {"High (nice graphics)", "Hoch (schöne Grafik)"},
    {"High background load", "Hintergrundlast hoch"},
    {"High jitter, probably radio interference", "Jitter hoch, vermutlich Funk-Störung"},
    {"High jitter, the line fluctuates", "Jitter hoch, die Leitung schwankt"},
    {"High ping ({:.0f} ms), server far away or poor route", "Ping hoch ({:.0f} ms), Server weit weg oder Route schlecht"},
    {"Highlight", "Hervorhebung"},
    {"Highlight enchanted", "Verzauberte hervorheben"},
    {"Highlight words", "Wörter hervorheben"},
    {"History height", "Verlauf-Höhe"},
    {"Hit", "Treffer"},
    {"Hit detection needs the AttackEntity signature. \"Every click\" always works.", "Treffer-Erkennung braucht die Signatur AttackEntity. Mit \"Klick\" geht es immer."},
    {"Hit feedback", "Treffer-Feedback"},
    {"Hit ping", "Hit-Ping"},
    {"Hit rate", "Trefferquote"},
    {"Hit visuals", "Treffer-Visuals"},
    {"Hitbox color", "Hitbox-Farbe"},
    {"Hitboxes", "Hitboxen"},
    {"Hits", "Treffer"},
    {"Hits in the average", "Treffer im Durchschnitt"},
    {"Hits, swings and hit rate of the current round.", "Treffer, Schwünge und Trefferquote der aktuellen Runde."},
    {"Hold", "Halten"},
    {"Hold key", "Halte-Taste"},
    {"Hold the hand lower", "Hand tiefer halten"},
    {"Hotkey", "Taste"},
    {"Hotkeys for chat commands like /hub. Opens the chat like a player and sends the command.", "Tastenkürzel für Chat-Befehle wie /hub. Öffnet den Chat wie ein Spieler und sendet den Befehl."},
    {"Hotkeys for ready-made chat messages.", "Tastenkürzel für fertige Chat-Nachrichten."},
    {"Hue", "Farbton"},
    {"Hunger color", "Hungerfarbe"},
    {"Hunger {:.0f}  ·  Saturation {:.1f}", "Hunger {:.0f}  ·  Sättigung {:.1f}"},
    {"Hurt animation", "Treffer-Animation"},
    {"Hurt camera shake", "Treffer-Wackeln"},
    {"Hurt color", "Trefferfarbe"},
    {"Icon", "Symbol"},
    {"Icon size", "Symbolgröße"},
    {"Ignore repeats within (ms)", "Wiederholungen ignorieren innerhalb (ms)"},
    {"In chunk", "Im Chunk"},
    {"In hearts", "In Herzen"},
    {"Include the server tick", "Server-Tick einrechnen"},
    {"Input", "Eingabe"},
    {"Instant Damage", "Sofortschaden"},
    {"Instant Health", "Sofortheilung"},
    {"Inventory delay", "Inventar-Verzögerung"},
    {"Inventory info", "Inventar-Info"},
    {"Invert Y axis", "Y-Achse umkehren"},
    {"Invisibility", "Unsichtbarkeit"},
    {"Item in hand", "Item in der Hand"},
    {"Item name", "Item-Name"},
    {"Item name (e.g. golden_apple)", "Item-Name (z. B. golden_apple)"},
    {"Item physics", "Item-Physik"},
    {"Item size", "Item-Größe"},
    {"Item use delay", "Item-Nutzungs-Verzögerung"},
    {"Items (name=seconds, comma separated)", "Items (name=Sekunden, mit Komma)"},
    {"JPEG quality", "JPEG-Qualität"},
    {"Java-style FOV changes: sprinting, speed and drawing a bow change the view smoothly.", "Sichtfeld-Änderungen wie in Java: Sprinten, Schnelligkeit und Bogenspannen verändern das Bild sanft."},
    {"Java-style debug display: FPS, position, chunk, biome, memory, renderer.", "Debug-Anzeige im Java-Stil: FPS, Position, Chunk, Biom, Speicher, Renderer."},
    {"Java-style player list with columns, ping and sorting.", "Spielerliste im Java-Stil mit Spalten, Ping und Sortierung."},
    {"Jitter bad from (ms)", "Jitter schlecht ab (ms)"},
    {"Jitter medium from (ms)", "Jitter mittel ab (ms)"},
    {"Join words (comma)", "Beitritts-Wörter (Komma)"},
    {"Jump Boost", "Sprungkraft"},
    {"K/D", "K/D"},
    {"Keep pitch", "Neigung beibehalten"},
    {"Key ", "Taste "},
    {"Key in game", "Taste im Spiel"},
    {"Kill streak words (comma)", "Kill-Serien-Wörter (Komma)"},
    {"Kill!", "Kill!"},
    {"Kill: ", "Kill: "},
    {"Kills and deaths", "Kills und Tode"},
    {"Kills, deaths, K/D and kill streak of this session.", "Kills, Tode, K/D und Kill-Serie dieser Sitzung."},
    {"Label", "Beschriftung"},
    {"Last commands", "Letzte Befehle"},
    {"Last frame: %.2f ms (%.0f FPS)", "Letzter Frame: %.2f ms (%.0f FPS)"},
    {"Last hit", "Letzter Treffer"},
    {"Last pressed key wins", "Zuletzt gedrückte Taste gewinnt"},
    {"Layout", "Anordnung"},
    {"Leave words (comma)", "Verlassen-Wörter (Komma)"},
    {"Left / Right", "Links / Rechts"},
    {"Left click paints, right click erases", "Linksklick malt, Rechtsklick löscht"},
    {"Left column", "Linke Spalte"},
    {"Length", "Länge"},
    {"Level", "Stufe"},
    {"Levitation", "Schwebekraft"},
    {"Lifetime (s)", "Lebensdauer (s)"},
    {"Light beam", "Lichtstrahl"},
    {"Line background", "Zeilen-Hintergrund"},
    {"Long break", "Lange Pause"},
    {"Long break (min)", "Lange Pause (min)"},
    {"Longest first", "Längste zuerst"},
    {"Look key", "Blick-Taste"},
    {"Look movement", "Blickbewegung"},
    {"Loss bad from (%)", "Verlust schlecht ab (%)"},
    {"Low", "Niedrig"},
    {"Low (maximum FPS)", "Niedrig (maximale FPS)"},
    {"Low FPS", "Niedrige FPS"},
    {"Low below (FPS)", "Niedrig ab (FPS)"},
    {"Lower", "Absenken"},
    {"Lowers the fire overlay at the bottom of the screen or hides it completely.", "Senkt das Feuer-Overlay am unteren Bildrand oder blendet es ganz aus."},
    {"Main color", "Hauptfarbe"},
    {"Map avoider", "Map Avoider"},
    {"Map vote", "Map-Abstimmung"},
    {"Map vote helper", "Map-Vote-Hilfe"},
    {"Match end words (comma)", "Wörter für Match-Ende (Komma)"},
    {"Match over", "Match vorbei"},
    {"Maximum brightness everywhere, with a smooth fade and optionally only at night.", "Maximale Helligkeit überall, mit weichem Übergang und optional nur nachts oder in Höhlen."},
    {"Maximum distance (0 = unlimited)", "Maximale Entfernung (0 = unbegrenzt)"},
    {"Maximum lines", "Maximale Zeilen"},
    {"Measurement interval (ms)", "Messabstand (ms)"},
    {"Measurement interval (s)", "Messabstand (s)"},
    {"Measurement method", "Messverfahren"},
    {"Medium", "Mittel"},
    {"Mega", "Mega"},
    {"Menu limit", "Menü-Limit"},
    {"Merge identical lines", "Gleiche Zeilen zusammenfassen"},
    {"Message after kill", "Nachricht nach Kill"},
    {"Messages (random, separate with |)", "Nachrichten (zufällig, mit | trennen)"},
    {"Min / avg / max", "Min / Mittel / Max"},
    {"Min {:.0f}  ·  Avg {:.0f}  ·  Max {:.0f} ms", "Min {:.0f}  ·  Mittel {:.0f}  ·  Max {:.0f} ms"},
    {"Minimum gap (s)", "Mindestabstand (s)"},
    {"Minimum gap between requeues (s)", "Mindestabstand zwischen Requeues (s)"},
    {"Minimum time between hits (ms)", "Mindestabstand zwischen Treffern (ms)"},
    {"Mining Fatigue", "Abbaulähmung"},
    {"Minutes per day", "Minuten pro Tag"},
    {"Mirror", "Spiegeln"},
    {"Mix", "Mischen"},
    {"MochiPlayer", "MochiSpieler"},
    {"Mode", "Modus"},
    {"Model", "Modell"},
    {"Modules and their signatures", "Module und ihre Signaturen"},
    {"Modules that get hidden (comma)", "Module, die versteckt werden (Komma)"},
    {"More or fewer particles. Fewer helps FPS, more looks nicer.", "Mehr oder weniger Partikel. Weniger hilft den FPS, mehr sieht schöner aus."},
    {"Motion blur from camera movement and frame blending. Strength, quality and threshold adjustable.", "Bewegungsunschärfe aus Kamerabewegung und Bildmischung. Stärke, Qualität und Schwelle einstellbar."},
    {"Move closer to the router or use a LAN cable", "Näher an den Router oder LAN-Kabel nutzen"},
    {"Movement", "Bewegung"},
    {"Multiply", "Multiplizieren"},
    {"Murder Mystery: requeue as Innocent", "Murder Mystery: als Innocent neu einreihen"},
    {"Murder Mystery: requeue as Murderer", "Murder Mystery: als Murderer neu einreihen"},
    {"Murder Mystery: requeue as Sheriff", "Murder Mystery: als Sheriff neu einreihen"},
    {"Murderer", "Murderer"},
    {"NE", "NO"},
    {"Name and distance of the opponent you aim at, health only on request.", "Name und Distanz des anvisierten Gegners, Leben nur auf Wunsch."},
    {"Name the biggest share", "Größten Anteil nennen"},
    {"Names (comma)", "Namen (Komma)"},
    {"Nausea", "Übelkeit"},
    {"Negative effects", "Negative Effekte"},
    {"Nether conversion", "Nether-Umrechnung"},
    {"Network", "Netzwerk"},
    {"Network share", "Netzwerk-Anteil"},
    {"Never", "Nie"},
    {"Next", "Weiter"},
    {"Night", "Nacht"},
    {"Night Vision", "Nachtsicht"},
    {"No death yet", "Noch kein Tod"},
    {"No effects", "Keine Effekte"},
    {"No limit active  ·  Monitor: %d Hz", "Kein Limit aktiv  ·  Monitor: %d Hz"},
    {"No line selected", "Keine Zeile gewählt"},
    {"No measurement", "Keine Messung"},
    {"No pack", "Kein Pack"},
    {"No reply", "Keine Antwort"},
    {"No reply from the server. Is the firewall blocking ICMP?", "Keine Antwort vom Server. Blockiert die Firewall ICMP?"},
    {"North", "Norden"},
    {"Northeast", "Nordosten"},
    {"Northwest", "Nordwesten"},
    {"Not allowed on many servers. Only turn it on where the server rules allow it.", "Auf vielen Servern nicht erlaubt. Nur einschalten, wenn die Server-Regeln es zulassen."},
    {"Not on The Hive. This module only works there.", "Nicht auf The Hive. Dieses Modul funktioniert nur dort."},
    {"Not on Zeqa. This module only works there.", "Nicht auf Zeqa. Dieses Modul funktioniert nur dort."},
    {"Notice on a poor connection", "Hinweis bei schlechter Verbindung"},
    {"Notice on change", "Hinweis beim Wechsel"},
    {"Notice on death", "Hinweis beim Tod"},
    {"Notice on high load", "Hinweis bei hoher Last"},
    {"Notice on low FPS", "Hinweis bei niedrigen FPS"},
    {"Number", "Zahl"},
    {"Number and percent", "Zahl und Prozent"},
    {"Number color", "Zahlenfarbe"},
    {"Number of tips", "Anzahl Tipps"},
    {"Numbers", "Zahlen"},
    {"Numbers on the right", "Zahlen rechts"},
    {"Offhand", "Nebenhand"},
    {"Offset (FPS)", "Abzug (FPS)"},
    {"Offset X", "Versatz X"},
    {"Offset Y", "Versatz Y"},
    {"On click", "Bei Klick"},
    {"On the clipboard.", "In der Zwischenablage."},
    {"On this server the message on a kill is banned and disabled.", "Auf diesem Server ist die Nachricht beim Kill verboten und deaktiviert."},
    {"On/off key", "Ein/Aus-Taste"},
    {"One block with selectable lines: FPS, CPS, Ping, position, health, clock, RAM.", "Ein Block mit wählbaren Zeilen: FPS, CPS, Ping, Position, Leben, Uhr, RAM."},
    {"One line", "Eine Zeile"},
    {"Only against full armor", "Nur gegen volle Rüstung"},
    {"Only at certain hours", "Nur zu bestimmter Uhrzeit"},
    {"Only at night", "Nur nachts"},
    {"Only for mobs", "Nur bei Mobs"},
    {"Only for players", "Nur bei Spielern"},
    {"Only in solo modes", "Nur in Solo-Modi"},
    {"Only lines containing (empty = all)", "Nur Zeilen mit (leer = alle)"},
    {"Only on crit", "Nur bei Crit"},
    {"Only simulate instead of correcting", "Nur simulieren statt korrigieren"},
    {"Only underwater", "Nur unter Wasser"},
    {"Only when in hand", "Nur wenn in der Hand"},
    {"Only while Tab is held", "Nur solange Tab gehalten wird"},
    {"Only while a key is held", "Nur solange eine Taste gehalten wird"},
    {"Only while sprinting", "Nur beim Sprinten"},
    {"Only while the camera moves", "Nur bei Kamerabewegung"},
    {"Only while the menu is open", "Nur bei offenem Menü"},
    {"Only while walking", "Nur beim Gehen"},
    {"Only while zooming", "Nur beim Zoomen"},
    {"Only with a bow", "Nur mit Bogen"},
    {"Only with an empty hand", "Nur bei leerer Hand"},
    {"Open folder", "Ordner öffnen"},
    {"Opponent", "Gegner"},
    {"Opponent reach", "Gegner-Reach"},
    {"Opposite direction keys no longer cancel each other. Banned on many servers.", "Gegenläufige Richtungstasten heben sich nicht auf. Auf vielen Servern verboten."},
    {"Original block outline", "Original-Blockumriss"},
    {"Other programs use {:.0f}% of the CPU.", "Andere Programme nutzen {:.0f}% der CPU."},
    {"Outline color", "Umriss-Farbe"},
    {"Outline enchanted", "Verzauberte umranden"},
    {"Outline thickness", "Umriss-Dicke"},
    {"Overall size", "Größe gesamt"},
    {"Overlay", "Überlagern"},
    {"Overlay cost", "Overlay-Kosten"},
    {"Overlay {:.2f} ms per frame", "Overlay {:.2f} ms pro Frame"},
    {"Overworld", "Oberwelt"},
    {"Own nametag", "Eigener Nametag"},
    {"Own selection", "Eigene Auswahl"},
    {"Own sensitivity while you draw the bow, for more precise aiming.", "Eigene Empfindlichkeit, solange du den Bogen spannst, für präziseres Zielen."},
    {"Own sensitivity while zooming, drawing a bow, blocking, sneaking and sprinting.", "Eigene Empfindlichkeit beim Zoomen, Bogenspannen, Blocken, Schleichen und Sprinten."},
    {"Own values", "Eigene Werte"},
    {"Own words", "Eigene Wörter"},
    {"Packet loss", "Paketverlust"},
    {"Pants", "Hose"},
    {"Particle amount", "Partikelmenge"},
    {"Particles", "Partikel"},
    {"Particles and sparks at the crosshair on hits. Local only, visible only to you.", "Partikel und Funken am Fadenkreuz bei Treffern. Nur lokal, nur für dich sichtbar."},
    {"Particles off", "Partikel aus"},
    {"Party accept command", "Befehl zum Annehmen von Partys"},
    {"Party invite words (comma)", "Wörter für Party-Einladungen (Komma)"},
    {"Paste code", "Code einfügen"},
    {"Pastel", "Pastell"},
    {"Pause background downloads and cloud sync", "Hintergrund-Downloads und Cloud-Sync pausieren"},
    {"Per server", "Pro Server"},
    {"Percent", "Prozent"},
    {"Permanent", "Dauerhaft"},
    {"Perspective", "Perspektive"},
    {"Pill", "Pille"},
    {"Ping as bars", "Ping als Balken"},
    {"Ping bad", "Ping schlecht"},
    {"Ping bad from (ms)", "Ping schlecht ab (ms)"},
    {"Ping good", "Ping gut"},
    {"Ping history", "Ping-Verlauf"},
    {"Ping medium", "Ping mittel"},
    {"Ping medium from (ms)", "Ping mittel ab (ms)"},
    {"Ping spikes every {:.0f} s, probably a Wi-Fi scan in the background", "Ping-Spitzen alle {:.0f} s, vermutlich WLAN-Scan im Hintergrund"},
    {"Ping, jitter and packet loss to the server, plus Wi-Fi data and tips.", "Ping, Jitter und Paketverlust zum Server, plus WLAN-Daten und Tipps."},
    {"Pitch", "Tonhöhe"},
    {"Pixel editor (used for the shape \"Custom grid\")", "Pixel-Editor (wird bei Form \"Eigenes Raster\" benutzt)"},
    {"Pixel size", "Pixelgröße"},
    {"Play crit sound", "Crit-Ton anhören"},
    {"Play sound", "Ton anhören"},
    {"Player left", "Spieler weg"},
    {"Player look rotation", "Blickdrehung des Spielers"},
    {"Player online", "Spieler online"},
    {"Players", "Spieler"},
    {"Players only", "Nur Spieler"},
    {"Plays the hurt animation of the player you hit right away instead of after the server reply. Banned on many servers.", "Spielt die Treffer-Animation des getroffenen Spielers sofort, statt erst nach der Server-Antwort. Auf vielen Servern verboten."},
    {"Plays your own sound on every hit. Local only, creates no network packet.", "Spielt bei jedem Treffer einen eigenen Ton ab. Nur lokal, erzeugt kein Netzwerkpaket."},
    {"Point {}", "Punkt {}"},
    {"Poison", "Vergiftung"},
    {"Poor", "Schlecht"},
    {"Position in chunk", "Position im Chunk"},
    {"Positive effects", "Positive Effekte"},
    {"Post effects", "Post-Effekte"},
    {"Potion effect strength", "Stärke der Trank-Effekte"},
    {"Potion value (-1 = any)", "Trank-Wert (-1 = egal)"},
    {"Power saving notice", "Energiespar-Hinweis"},
    {"Precise FPS limiter, throttles in the background and in the menu.", "Präziser FPS-Limiter, drosselt im Hintergrund und im Menü."},
    {"Prefix the server name", "Servername davorsetzen"},
    {"Preset", "Vorlage"},
    {"Preview for food in hand", "Vorschau für Essen in der Hand"},
    {"Processor: %d cores  ·  Memory: %.0f GB  ·  Video memory: %.0f GB", "Prozessor: %d Kerne  ·  Arbeitsspeicher: %.0f GB  ·  Grafikspeicher: %.0f GB"},
    {"Profile ", "Profil "},
    {"Profile applied", "Profil angewendet"},
    {"Profile not found", "Profil nicht gefunden"},
    {"Profile switched", "Profil gewechselt"},
    {"Promo words (comma)", "Werbe-Wörter (Komma)"},
    {"Pulse", "Pulsieren"},
    {"Pulse depth", "Puls-Tiefe"},
    {"Pulse speed (Hz)", "Puls-Tempo (Hz)"},
    {"Pulse while clicking", "Pulsieren beim Klicken"},
    {"Pulsing", "Pulsierend"},
    {"Put /cs in front of the code", "/cs vor den Code setzen"},
    {"Puts a color filter over the game image, for example a soft pink.", "Legt einen Farbfilter über das Spielbild, zum Beispiel zartes Rosa."},
    {"Quality (samples)", "Qualität (Proben)"},
    {"Queue", "Warteschlange"},
    {"Queue command ({type} {mode})", "Queue-Befehl ({type} {mode})"},
    {"Rain", "Regen"},
    {"Rain strength", "Regenstärke"},
    {"Rainbow", "Regenbogen"},
    {"Rainbow speed", "Regenbogen-Tempo"},
    {"Range (chunks)", "Reichweite (Chunks)"},
    {"Ranked", "Ranked"},
    {"Recommendation: %s", "Empfehlung: %s"},
    {"Red below (s, 0 = off)", "Rot unter (s, 0 = aus)"},
    {"Red from (blocks)", "Rot ab (Blöcke)"},
    {"Red on hits", "Rot bei Treffern"},
    {"Red weakness (protanopia)", "Rotschwäche (Protanopie)"},
    {"Refresh rate minus offset", "Bildwiederholrate minus Abzug"},
    {"Remaining height change", "Restliche Höhenänderung"},
    {"Remaining strength", "Restliche Stärke"},
    {"Remaining totems", "Verbleibende Totems"},
    {"Remaining wait", "Restliche Wartezeit"},
    {"Remember level", "Stufe merken"},
    {"Remembered death points", "Gemerkte Todespunkte"},
    {"Remembers where you died and shows the last death points with coordinates.", "Merkt sich, wo du gestorben bist, und zeigt die letzten Todespunkte mit Koordinaten."},
    {"Remove color codes", "Farbcodes entfernen"},
    {"Render thread with higher priority", "Render-Thread mit höherer Priorität"},
    {"Requeue after a match", "Nach einem Match neu einreihen"},
    {"Requeue command", "Requeue-Befehl"},
    {"Requeue for duels after a match, chat cleanup and auto accept for Zeqa. Only runs on Zeqa.", "Requeue für Duelle nach dem Match, Chat aufräumen und Auto-Accept für Zeqa. Läuft nur auf Zeqa."},
    {"Requeue helper, map avoider, role requeue, chat cleanup and auto accept for The Hive. Only runs on The Hive.", "Requeue-Helfer, Map Avoider, Rollen-Requeue, Chat aufräumen und Auto-Accept für The Hive. Läuft nur auf The Hive."},
    {"Requeue key", "Requeue-Taste"},
    {"Requeue now", "Jetzt neu einreihen"},
    {"Reset after (s)", "Zurücksetzen nach (s)"},
    {"Reset after (s, 0 = never)", "Zurücksetzen nach (s, 0 = nie)"},
    {"Reset after a pause", "Nach einer Pause zurücksetzen"},
    {"Reset measurement", "Messung zurücksetzen"},
    {"Resistance", "Resistenz"},
    {"Right column", "Rechte Spalte"},
    {"Ring color by phase", "Ringfarbe nach Phase"},
    {"Rise", "Aufstieg"},
    {"Role {}", "Rolle {}"},
    {"Role: {}  ·  Deaths this game: {}", "Rolle: {}  ·  Tode in diesem Spiel: {}"},
    {"Roman numerals", "Römische Ziffern"},
    {"Rotation", "Drehung"},
    {"Rotation X", "Drehung X"},
    {"Rotation Y", "Drehung Y"},
    {"Rotation Z", "Drehung Z"},
    {"Round", "Runde"},
    {"Round counter", "Rundenzähler"},
    {"Round {}", "Runde {}"},
    {"Rounds until the long break", "Runden bis zur langen Pause"},
    {"Rows per column", "Zeilen pro Spalte"},
    {"Running", "Laufend"},
    {"SE", "SO"},
    {"Sakura petals fall gently across the screen.", "Sakura-Blütenblätter fallen sanft über den Bildschirm."},
    {"Samples in the window", "Messwerte im Fenster"},
    {"Saturation", "Sättigung"},
    {"Saturation color", "Sättigungsfarbe"},
    {"Save as file", "Als Datei speichern"},
    {"Saves the chat to a text file per day, with timestamps and filter.", "Speichert den Chat in einer Textdatei pro Tag, mit Zeitstempel und Filter."},
    {"Scale", "Skalierung"},
    {"Scales the game's interface in fine steps, beyond the normal levels.", "Skaliert die Oberfläche des Spiels in feinen Schritten, über die normalen Stufen hinaus."},
    {"Screenshot copied", "Screenshot kopiert"},
    {"Screenshot failed", "Screenshot fehlgeschlagen"},
    {"Screenshot on a key, with or without the Mochi HUD, as PNG or JPEG.", "Screenshot per Taste, mit oder ohne Mochi-HUD, als PNG oder JPEG."},
    {"Screenshot saved", "Screenshot gespeichert"},
    {"Second color", "Zweitfarbe"},
    {"Sends your position to Mumble for distance-based voice chat.", "Sendet deine Position an Mumble für Sprachchat nach Abstand."},
    {"Sensitive displays are off.", "Sensible Anzeigen sind aus."},
    {"Server code copied", "Server-Code kopiert"},
    {"Server=profile, separate with semicolons", "Server=Profil, mit Semikolon trennen"},
    {"Set a point at my position", "Punkt an meiner Position setzen"},
    {"Set the death point automatically", "Todespunkt automatisch setzen"},
    {"Set your field of view freely. Sprint and potion effects can be turned off.", "Stellt dein Sichtfeld frei ein. Sprint- und Trank-Effekte lassen sich abschalten."},
    {"Sets the time of day only for you: fixed, running or sunset.", "Stellt die Tageszeit nur bei dir ein: fest, laufend oder Sonnenuntergang."},
    {"Shadow", "Schatten"},
    {"Shadows off", "Schatten aus"},
    {"Shaky", "Wackelig"},
    {"Sharpens the game image, useful at low resolution or scaling.", "Schärft das Spielbild nach, nützlich bei niedriger Auflösung oder Skalierung."},
    {"Shift hue", "Farbton verschieben"},
    {"Shirt", "Oberteil"},
    {"Short break", "Kurze Pause"},
    {"Short break (min)", "Kurze Pause (min)"},
    {"Shortens the local chain from click to frame. Creates no clicks. Banned on some servers.", "Kürzt die lokale Kette Klick bis Bild. Erzeugt keine Klicks. Auf manchen Servern verboten."},
    {"Shortens the wait between item uses. Banned on many servers.", "Verkürzt die Wartezeit zwischen Item-Nutzungen. Auf vielen Servern verboten."},
    {"Shortest first", "Kürzeste zuerst"},
    {"Show a notice for every action", "Bei jeder Aktion einen Hinweis zeigen"},
    {"Show active effect channels", "Aktive Effekt-Kanäle zeigen"},
    {"Show armor", "Rüstung anzeigen"},
    {"Show at most", "Maximal anzeigen"},
    {"Show color codes", "Farbcodes darstellen"},
    {"Show distance", "Entfernung zeigen"},
    {"Show grid", "Raster anzeigen"},
    {"Show health", "Leben anzeigen"},
    {"Show in hearts", "In Herzen anzeigen"},
    {"Show notice", "Hinweis anzeigen"},
    {"Show peak value", "Höchstwert anzeigen"},
    {"Show percent", "Prozent anzeigen"},
    {"Show ping", "Ping anzeigen"},
    {"Show reach", "Reichweite zeigen"},
    {"Show reason", "Grund anzeigen"},
    {"Show record", "Rekord anzeigen"},
    {"Show swings", "Schwünge anzeigen"},
    {"Show text", "Text anzeigen"},
    {"Show tips", "Tipps anzeigen"},
    {"Show unit", "Einheit anzeigen"},
    {"Shown death points", "Angezeigte Todespunkte"},
    {"Shown programs", "Angezeigte Programme"},
    {"Shows a message and plays a sound when one of your totems is used up.", "Zeigt eine Meldung und spielt einen Ton, wenn ein Totem bei dir verbraucht wird."},
    {"Shows cooldowns, for example for ender pearls. You choose which items count.", "Zeigt Abklingzeiten, zum Beispiel für Enderperlen. Welche Items zählen, legst du selbst fest."},
    {"Shows hitboxes with the game's own drawing path, so not through walls. Color adjustable.", "Zeigt die Hitboxen mit dem eigenen Zeichenweg des Spiels, also nicht durch Wände. Farbe einstellbar."},
    {"Shows how far your bow is drawn, right at the crosshair.", "Zeigt, wie weit dein Bogen gespannt ist, direkt am Fadenkreuz."},
    {"Shows hunger and saturation as a bar and previews what the food in your hand gives.", "Zeigt Hunger und Sättigung als Balken und rechnet vor, was das Essen in deiner Hand bringt."},
    {"Shows programs that use a lot of CPU and hurt FPS or ping.", "Zeigt Programme, die viel CPU ziehen und FPS oder Ping stören."},
    {"Shows the break progress of the block you are mining, at the crosshair.", "Zeigt den Abbaufortschritt des Blocks, den du gerade abbaust, am Fadenkreuz."},
    {"Shows the chunk borders around you as lines, with sub-chunks, range and colors.", "Zeigt die Chunk-Grenzen um dich als Linien, mit Unterchunks, Reichweite und Farben."},
    {"Shows the distance from which the opponent last hit you.", "Zeigt die Distanz, aus der dich der Gegner zuletzt getroffen hat."},
    {"Shows the distance of your last hit, as average or best value.", "Zeigt die Distanz deines letzten Treffers, als Durchschnitt oder Bestwert."},
    {"Shows the game day and the world time.", "Zeigt den Spieltag und die Spielzeit der Welt."},
    {"Shows the item in your hand with count and durability.", "Zeigt das Item in deiner Hand mit Menge und Haltbarkeit."},
    {"Shows the server address. Can be hidden for streamers.", "Zeigt die Server-Adresse. Für Streamer lässt sie sich verstecken."},
    {"Shows what you are looking at: block or entity with name, distance and break progress.", "Zeigt, was du gerade anschaust: Block oder Entity mit Name, Distanz und Abbaufortschritt."},
    {"Shows whether your last hit was a critical hit, and the crit rate.", "Zeigt, ob dein letzter Schlag ein kritischer Treffer war, und die Crit-Quote."},
    {"Shows which modules run on this version. Also home of the demo data switch.", "Zeigt, welche Module auf dieser Version laufen. Hier gibt es auch Demo-Daten."},
    {"Shows which resource packs are active.", "Zeigt, welche Resource Packs gerade aktiv sind."},
    {"Shows yaw and pitch of your view direction.", "Zeigt Yaw und Pitch deiner Blickrichtung."},
    {"Shows your active effects with time left, sorted and colored. Turns red when an effect is about to run out.", "Zeigt deine aktiven Effekte mit Restzeit, sortiert und farbig. Wird rot, wenn ein Effekt gleich ausläuft."},
    {"Shows your armor and the item in your hand with durability as a number, percent or bar.", "Zeigt deine Rüstung und das Item in der Hand mit Haltbarkeit als Zahl, Prozent oder Balken."},
    {"Shows your health as a number, hearts or bar, with absorption.", "Zeigt dein Leben als Zahl, Herzen oder Balken, mit Absorption."},
    {"Shows your level and the progress to the next level.", "Zeigt dein Level und den Fortschritt zum nächsten Level."},
    {"Shows your ping to the server.", "Zeigt deinen Ping zum Server."},
    {"Shows your position, optionally with chunk, biome, facing and Nether conversion.", "Zeigt deine Position, auf Wunsch mit Chunk, Biom, Himmelsrichtung und Nether-Umrechnung."},
    {"Shows your speed in blocks per second.", "Zeigt deine Geschwindigkeit in Blöcken pro Sekunde."},
    {"Shrink while sneaking", "Zusammenziehen beim Schleichen"},
    {"Side by side", "Nebeneinander"},
    {"Signatures: {}/{} ({})", "Signaturen: {}/{} ({})"},
    {"Skin color", "Hautfarbe"},
    {"Skip phase", "Phase überspringen"},
    {"Sky", "Himmel"},
    {"Sky off", "Himmel aus"},
    {"Sleeps when idle", "Schläft bei Inaktivität"},
    {"Slight fluctuations", "Leichte Schwankungen"},
    {"Slot ", "Platz "},
    {"Slow Falling", "Sanftes Fallen"},
    {"Slowness", "Langsamkeit"},
    {"Smooth fade", "Sanfter Übergang"},
    {"Smoothing", "Glättung"},
    {"Smoothing (s)", "Glättung (s)"},
    {"Sneak camera", "Schleich-Kamera"},
    {"Sneaking stays on until you press the sneak key again.", "Schleichen bleibt an, bis du die Schleich-Taste noch einmal drückst."},
    {"Soft focus: the image gets blurry towards the edges, like a camera with a tilt-shift effect.", "Weicher Fokus: das Bild wird zum Rand hin unscharf, wie bei einer Kamera mit Tilt-Shift-Effekt."},
    {"Soft, gliding camera movement like in film shots. Optionally only while zooming.", "Weiche, gleitende Kamerabewegung wie in Filmaufnahmen. Auf Wunsch nur beim Zoomen."},
    {"Solos", "Solo"},
    {"Sorting", "Sortierung"},
    {"Sound", "Ton"},
    {"Sound on crit", "Ton bei Crit"},
    {"South", "Süden"},
    {"Southeast", "Südosten"},
    {"Southwest", "Südwesten"},
    {"Spacing", "Abstand"},
    {"Sparks", "Funken"},
    {"Speed: {:.2f} b/s", "Tempo: {:.2f} b/s"},
    {"Spin speed (°/s)", "Dreh-Tempo (°/s)"},
    {"Splits the delay into input, frame, network and server tick.", "Teilt die Verzögerung in Eingabe, Bild, Netzwerk und Server-Tick auf."},
    {"Spread", "Streuung"},
    {"Spread while clicking", "Aufweiten beim Klicken"},
    {"Spread while jumping", "Aufweiten beim Springen"},
    {"Spread while walking", "Aufweiten beim Laufen"},
    {"Sprint and potion effects off", "Sprint- und Trank-Effekte aus"},
    {"Sprinting stays on until you press the key again.", "Sprinten bleibt an, bis du die Taste noch einmal drückst."},
    {"Squads", "Squads"},
    {"Square", "Quadrat"},
    {"Stable", "Stabil"},
    {"Stacked", "Untereinander"},
    {"Stars", "Sterne"},
    {"Start / pause", "Start / Pause"},
    {"Start level", "Start-Level"},
    {"Start the next phase automatically", "Nächste Phase automatisch starten"},
    {"Statistics", "Statistik"},
    {"Step size", "Schrittweite"},
    {"Streak", "Serie"},
    {"Streak {} (best {})", "Serie {} (Rekord {})"},
    {"Strength", "Stärke"},
    {"Study and break timer: work phase, short and long break, with a notice on every change.", "Lern- und Pausen-Timer: Arbeitsphase, kurze und lange Pause, mit Hinweis beim Wechsel."},
    {"Sub-chunk levels", "Unterchunk-Ebenen"},
    {"Summary when you leave a server: duration, hits, combo, K/D.", "Zusammenfassung beim Verlassen eines Servers: Dauer, Treffer, Combo, K/D."},
    {"Summary: ", "Zusammenfassung: "},
    {"Sunset", "Sonnenuntergang"},
    {"Swing duration", "Schwung-Dauer"},
    {"Swing speed", "Schwunggeschwindigkeit"},
    {"Switch back afterwards", "Danach zurückwechseln"},
    {"Switch back when leaving", "Beim Verlassen zurückwechseln"},
    {"Switch to the 5 GHz band, 2.4 GHz is crowded", "Auf das 5-GHz-Band wechseln, 2,4 GHz ist überlaufen"},
    {"Switches between your saved settings profiles on a key.", "Wechselt per Taste zwischen deinen gespeicherten Einstellungs-Profilen."},
    {"Switches the perspective automatically, for example when gliding or drawing a bow.", "Wechselt die Perspektive automatisch, etwa beim Gleiten oder Bogenspannen."},
    {"T shape", "T-Form"},
    {"Teaming words (comma)", "Teaming-Wörter (Komma)"},
    {"Tells you when a player from your list joins the server, for example friends.", "Meldet, wenn ein Spieler aus deiner Liste auf den Server kommt, zum Beispiel Freunde."},
    {"Text size", "Textgröße"},
    {"Text when off", "Text wenn aus"},
    {"Text when on", "Text wenn aktiv"},
    {"The camera no longer drops when you sneak.", "Die Kamera springt beim Schleichen nicht mehr nach unten."},
    {"The camera no longer shakes when you get hit. The strength is adjustable.", "Die Kamera wackelt nicht mehr, wenn du getroffen wirst. Die Stärke ist regelbar."},
    {"The file could not be written.", "Die Datei konnte nicht geschrieben werden."},
    {"Third person back", "Dritte Person hinten"},
    {"Third person front", "Dritte Person vorne"},
    {"Threshold (pixels per frame)", "Schwelle (Pixel pro Frame)"},
    {"Throttle in the background", "Im Hintergrund drosseln"},
    {"Throttle while the menu is open", "Bei offenem Menü drosseln"},
    {"Thunder off only", "Nur Gewitter aus"},
    {"Thunderstorm", "Gewitter"},
    {"Tick interval (ms)", "Tick-Raster (ms)"},
    {"Time from your attack until the server confirms the hit.", "Zeit von deinem Angriff, bis der Server den Treffer bestätigt."},
    {"Time left", "Restzeit"},
    {"Time of day", "Tageszeit"},
    {"Time since death", "Zeit seit dem Tod"},
    {"Time-left bar", "Restzeit-Balken"},
    {"Time: {} (day {})  {}", "Zeit: {} (Tag {})  {}"},
    {"Timestamp", "Zeitstempel"},
    {"Title", "Titel"},
    {"Toggle", "Umschalten"},
    {"Toggle with the key", "Taste umschalten"},
    {"Total damage", "Gesamtschaden"},
    {"Totem used", "Totem verbraucht"},
    {"Totem used ({} left)", "Totem verbraucht ({} übrig)"},
    {"Traffic light", "Ampel"},
    {"Transition speed", "Übergangstempo"},
    {"Triangle", "Dreieck"},
    {"Trigger", "Auslöser"},
    {"Try to exclude team", "Team ausschließen (Versuch)"},
    {"Turn off power saving of the Wi-Fi adapter in the Device Manager", "Energiesparen des WLAN-Adapters im Geräte-Manager abschalten"},
    {"Turn off sky, fog and clouds one by one, only for you.", "Himmel, Nebel und Wolken einzeln abschalten, nur für dich."},
    {"Turn off the driver's automatic Wi-Fi scan", "Automatische WLAN-Suche des Treibers abschalten"},
    {"Turn the camera freely around you while your body and walking direction stay. Banned on some servers.", "Kamera frei um dich drehen, während Körper und Laufrichtung bleiben. Auf manchen Servern verboten."},
    {"Turns off expensive graphics like clouds, particles and shadows one by one.", "Schaltet teure Grafik wie Wolken, Partikel und Schatten einzeln ab."},
    {"Turns off the bobbing while walking, separately for camera and hand.", "Schaltet das Wackeln beim Laufen ab, für Kamera und Hand getrennt."},
    {"Turns the game image upside down. Controls stay normal, on purpose.", "Dreht das Spielbild auf den Kopf. Die Steuerung bleibt normal, das ist Absicht."},
    {"Type", "Art"},
    {"Unit", "Einheit"},
    {"Unlock words (comma)", "Freischalt-Wörter (Komma)"},
    {"Unranked", "Unranked"},
    {"Until (hour)", "Bis (Uhr)"},
    {"Value", "Wert"},
    {"Variant (-1 = any)", "Variante (-1 = egal)"},
    {"Version %s  ·  %d of %d signatures  ·  Source %s", "Version %s  ·  %d von %d Signaturen  ·  Quelle %s"},
    {"Vertical", "Vertikal"},
    {"Vignette off", "Vignette aus"},
    {"Visible for (s)", "Sichtbar für (s)"},
    {"Visible lines", "Sichtbare Zeilen"},
    {"Vivid", "Lebendig"},
    {"Volume", "Lautstärke"},
    {"Vote for {}", "Stimme für {}"},
    {"Waiting for the server", "Warte auf Server"},
    {"Warn below (%)", "Warnen unter (%)"},
    {"Warn from (% CPU)", "Warnen ab (% CPU)"},
    {"Warning color", "Warnfarbe"},
    {"Warning color at most (0 = off)", "Warnfarbe bei höchstens (0 = aus)"},
    {"Warns in the middle of the screen when armor or tools are almost broken, with an optional sound.", "Warnt in der Bildschirmmitte, wenn Rüstung oder Werkzeug fast kaputt sind, mit optionalem Ton."},
    {"Water Breathing", "Wasseratmung"},
    {"Water color", "Wasserfarbe"},
    {"Weak Wi-Fi signal ({} %)", "WLAN-Signal schwach ({} %)"},
    {"Weakens the bobbing while walking. You set the strength yourself.", "Schwächt das Wackeln beim Laufen ab. Die Stärke stellst du selbst ein."},
    {"Weakness", "Schwäche"},
    {"Weather", "Wetter"},
    {"Weather effects off", "Wetter-Effekte aus"},
    {"West", "Westen"},
    {"When", "Wann"},
    {"While blocking", "Beim Blocken"},
    {"While drawing a bow", "Beim Bogenspannen"},
    {"While gliding", "Beim Gleiten"},
    {"While sneaking", "Beim Schleichen"},
    {"While sprinting", "Beim Sprinten"},
    {"While zooming", "Beim Zoomen"},
    {"Wi-Fi", "WLAN"},
    {"Width", "Breite"},
    {"Window: {:.0f}x{:.0f}", "Fenster: {:.0f}x{:.0f}"},
    {"With Mochi HUD", "Mit Mochi-HUD"},
    {"Without Mochi HUD", "Ohne Mochi-HUD"},
    {"Words (comma)", "Wörter (Komma)"},
    {"Words in chat (comma)", "Wörter im Chat (Komma)"},
    {"Work", "Arbeiten"},
    {"Work (min)", "Arbeit (min)"},
    {"World", "Welt"},
    {"You died", "Du bist gestorben"},
    {"Your own crosshair with many shapes, a pixel editor and dynamics.", "Eigenes Fadenkreuz mit vielen Formen, Pixel-Editor und Dynamik."},
    {"Your own fog color, optionally as a rainbow.", "Eigene Nebelfarbe, auf Wunsch als Regenbogen."},
    {"Your own markers with beam, name and distance, also as an edge arrow.", "Eigene Markierungen mit Beam, Name und Entfernung, auch als Randpfeil."},
    {"Your own movable chat with timestamps, filter and highlighting.", "Eigener, verschiebbarer Chat mit Zeitstempeln, Filter und Hervorhebung."},
    {"Your own movable scoreboard without red numbers.", "Eigenes, verschiebbares Scoreboard ohne rote Zahlen."},
    {"Your own outline for the block you look at: color, thickness, fill, rainbow and pulsing.", "Eigener Umriss für den Block, den du anschaust: Farbe, Dicke, Füllung, Regenbogen und Pulsieren."},
    {"Your own water color, for example clear turquoise or pink.", "Eigene Wasserfarbe, zum Beispiel klares Türkis oder Rosa."},
    {"Zoom key", "Zoom-Taste"},
    {"Zoom level", "Zoomstufe"},
    {"Zoom on a key with smooth animation, scroll wheel steps and adjusted sensitivity.", "Zoom per Taste mit weicher Animation, Scrollrad-Stufen und angepasster Empfindlichkeit."},
    {"Zoom when drawing a bow", "Zoom beim Bogenspannen"},
    {"[Sneak: off]", "[Schleichen: aus]"},
    {"[Sneak: on]", "[Schleichen: an]"},
    {"[Sprint: off]", "[Sprint: aus]"},
    {"[Sprint: on]", "[Sprint: an]"},
    {"active", "aktiv"},
    {"clear", "klar"},
    {"hidden", "versteckt"},
    {"missing: %s", "fehlt: %s"},
    {"requested", "angefordert"},
    {"{:.0f} / {:.0f} health", "{:.0f} / {:.0f} Leben"},
    {"{:.0f} FPS on average. Turn on the performance profile in the \"Auto Profile\" module.", "Im Schnitt {:.0f} FPS. Aktiviere im Modul \"Auto Profile\" das Performance-Profil."},
    {"{:.1f} % packet loss on the route", "{:.1f} % Paketverlust auf der Strecke"},
    {"{:.1f} % packet loss, probably radio interference", "{:.1f} % Paketverlust, vermutlich Funk-Störung"},
    {"{:.1f} blocks away", "{:.1f} Blöcke entfernt"},
    {"{}  ·  {} players", "{}  ·  {} Spieler"},
    {"{} (best {})", "{} (Rekord {})"},
    {"{} almost broken ({:.0f}%)", "{} fast kaputt ({:.0f}%)"},
    {"{} deaths", "{} Tode"},
    {"{}% system", "{}% System"},
    {"{}Loss {:.1f} %", "{}Verlust {:.1f} %"},
    {"§6Round 3 of 5 is starting", "§6Runde 3 von 5 startet"},
    {"§aMochi Wars: You won!", "§aMochi Wars: Du hast gewonnen!"},
    {"§eThe game starts in 5 seconds", "§eDas Spiel beginnt in 5 Sekunden"},
};

i18n::Table table(entries);

}
