#include "I18n.hpp"

namespace {

const i18n::Entry entries[] = {
    {"Info displays", "Info-Anzeigen"},
    {"Client Settings", "Client-Einstellungen"},
    {"Name tag behind your name in chat, notifications and other global options.", "Namens-Tag hinter deinem Namen im Chat, Benachrichtigungen und weitere globale Optionen."},
    {"Client tag", "Client-Tag"},
    {"Shown behind your own name in Better Chat and in the Tab List. Only you see it, nothing is sent to the server.", "Wird hinter deinem eigenen Namen im Better Chat und in der Tab-Liste angezeigt. Nur du siehst ihn, es wird nichts an den Server gesendet."},
    {"Client tag behind my name", "Client-Tag hinter meinem Namen"},
    {"Tag text", "Tag-Text"},
    {"Tag color", "Tag-Farbe"},
    {"Tag position", "Tag-Position"},
    {"Inside the name brackets", "In den Namens-Klammern"},
    {"Before the message", "Vor der Nachricht"},
    {"Tag in brackets", "Tag in Klammern"},
    {"Also in the Tab List", "Auch in der Tab-Liste"},
    {"Notifications", "Benachrichtigungen"},
    {"One switch for steady frame times: turns on System Boost, Low Latency and the Frame Limiter and pauses post effects and extras. Your old setup returns when you switch it off.", "Ein Schalter für gleichmäßige Frametimes: schaltet System Boost, Low Latency und den Frame Limiter ein und pausiert Post-Effekte und Extras. Dein altes Setup kommt zurück, sobald du ihn ausschaltest."},
    {"Pause post effects", "Post-Effekte pausieren"},
    {"Pause extras (pet, petals, games)", "Extras pausieren (Pet, Blütenblätter, Spiele)"},
    {"Maps to avoid (comma)", "Zu meidende Karten (Komma)"},
    {"Demo server", "Demo-Server"},
    {"Automatic", "Automatisch"},
    {"Slot 1", "Platz 1"},
    {"Slot 2", "Platz 2"},
    {"Slot 3", "Platz 3"},
    {"Slot 4", "Platz 4"},
    {"Slot 5", "Platz 5"},
    {"Slot 6", "Platz 6"},
    {"Slot 7", "Platz 7"},
    {"Slot 8", "Platz 8"},
    {"Slot 9", "Platz 9"},
    {"Key 1", "Taste 1"},
    {"Command 1", "Befehl 1"},
    {"Text 1", "Text 1"},
    {"Profile 1", "Profil 1"},
    {"Key 2", "Taste 2"},
    {"Command 2", "Befehl 2"},
    {"Text 2", "Text 2"},
    {"Profile 2", "Profil 2"},
    {"Key 3", "Taste 3"},
    {"Command 3", "Befehl 3"},
    {"Text 3", "Text 3"},
    {"Profile 3", "Profil 3"},
    {"Key 4", "Taste 4"},
    {"Command 4", "Befehl 4"},
    {"Text 4", "Text 4"},
    {"Profile 4", "Profil 4"},
    {"Key 5", "Taste 5"},
    {"Command 5", "Befehl 5"},
    {"Text 5", "Text 5"},
    {"Profile 5", "Profil 5"},
    {"Key 6", "Taste 6"},
    {"Command 6", "Befehl 6"},
    {"Text 6", "Text 6"},
    {"Profile 6", "Profil 6"},
    {"Key 7", "Taste 7"},
    {"Command 7", "Befehl 7"},
    {"Text 7", "Text 7"},
    {"Profile 7", "Profil 7"},
    {"Key 8", "Taste 8"},
    {"Command 8", "Befehl 8"},
    {"Text 8", "Text 8"},
    {"Profile 8", "Profil 8"},
    {"Key 9", "Taste 9"},
    {"Command 9", "Befehl 9"},
    {"Text 9", "Text 9"},
    {"Profile 9", "Profil 9"},
    {"Key 10", "Taste 10"},
    {"Command 10", "Befehl 10"},
    {"Text 10", "Text 10"},
    {"Profile 10", "Profil 10"},
    {"Key 11", "Taste 11"},
    {"Command 11", "Befehl 11"},
    {"Text 11", "Text 11"},
    {"Profile 11", "Profil 11"},
    {"Key 12", "Taste 12"},
    {"Command 12", "Befehl 12"},
    {"Text 12", "Text 12"},
    {"Profile 12", "Profil 12"},
};

i18n::Table table(entries);

}
